name: Deploy to Xserver

on:
  push:
    branches:
      - main  # mainブランチへのpush時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  deploy:
    name: Deploy WordPress Theme to Xserver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全履歴を取得

      # オプション1: FTP経由でデプロイ（フォールバック）
      - name: Deploy via FTP
        if: ${{ vars.DEPLOY_METHOD == 'ftp' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./euni-theme/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            **/*.log
            **/README.md

      # オプション2: SSH/rsync経由でデプロイ（SSH対応プランの場合）
      - name: Setup SSH Key
        if: ${{ vars.DEPLOY_METHOD == 'ssh' }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key

      - name: Create target directory if not exists
        if: ${{ vars.DEPLOY_METHOD == 'ssh' }}
        run: |
          ssh -i deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT || '10022' }} \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "mkdir -p ${{ secrets.SSH_TARGET_DIR }}"

      - name: Deploy via rsync
        if: ${{ vars.DEPLOY_METHOD == 'ssh' }}
        run: |
          rsync -auzrv --update \
            -e "ssh -i deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT || '10022' }}" \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='.DS_Store' \
            --exclude='Thumbs.db' \
            --exclude='*.log' \
            --delete \
            ./euni-theme/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_TARGET_DIR }}

      - name: Deployment Status
        if: success()
        run: |
          echo "✅ Deployment to Xserver completed successfully!"
          echo "Theme version: $(grep 'Version:' euni-theme/style.css | awk '{print $2}')"
          echo "Deployed at: $(date)"

      - name: Deployment Failed
        if: failure()
        run: |
          echo "❌ Deployment failed. Please check the logs above."
          exit 1
