name: Deploy to Xserver

on:
  push:
    branches:
      - main  # mainブランチへのpush時に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  deploy:
    name: Deploy WordPress Theme to Xserver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全履歴を取得

      # オプション1: FTP経由でデプロイ（SSH未対応プランの場合）
      - name: Deploy via FTP
        if: ${{ vars.DEPLOY_METHOD == 'ftp' || vars.DEPLOY_METHOD == '' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./euni-theme/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}  # 例: /home/username/domain.com/public_html/wp-content/themes/euni-theme/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            **/*.log
            **/README.md

      # オプション2: SSH/rsync経由でデプロイ（SSH対応プランの場合）
      - name: Deploy via SSH
        if: ${{ vars.DEPLOY_METHOD == 'ssh' }}
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SSH_PORT || '10022' }}  # Xserverのデフォルトは10022
          SOURCE: "euni-theme/"
          TARGET: ${{ secrets.SSH_TARGET_DIR }}  # 例: /home/username/domain.com/public_html/wp-content/themes/euni-theme/
          EXCLUDE: ".git, .github, node_modules, .DS_Store, Thumbs.db, *.log"
          ARGS: "-avz --delete"

      - name: Deployment Status
        if: success()
        run: |
          echo "✅ Deployment to Xserver completed successfully!"
          echo "Theme version: $(grep 'Version:' euni-theme/style.css | awk '{print $2}')"
          echo "Deployed at: $(date)"

      - name: Deployment Failed
        if: failure()
        run: |
          echo "❌ Deployment failed. Please check the logs above."
          exit 1
